### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by hamraee** [DigitalStrawberry/ANE-DeviceUtils#1]
Hello:
I use Adobe Animate.
How can I use this by Adobe Animate IDE?
Thanks in advance.

**Comment by marpies** [comment]
Hi,

You can follow [this guide](https://www.adobe.com/devnet/air/articles/using-ane-in-flash.html) for Flash Professional CS6. The steps should be basically the same for Adobe Animate.

If you still experience problems, let us know.
